# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aedeb8421f1d04c8787c1f214075b46b5d9a09946588a0b38a9e9e439ab478208b8dfb8f96c1d63a7782beecec26cd7b40178957380d580a7fd738f0d99170c6

test:
  secret_key_base: 66c28e3298a85ba5dd79c2df2f99b9e3fe6418d37701619e595bb3a43a2ca2edb224d8226331187dd0dacf52093651c60beac0a3d7fe2081d9e4f6be9b55e1eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
